### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by anaximander23** [devmondo/HangFire.SimpleInjector#13]
Hangfire.SimpleInjector doesn't seem to work in a project using ASP.NET Core; both Hangfire and SimpleInjector seem to work fine so this is likely just a matter of recompiling it as a .NET Core project. Shared projects could perhaps be used to avoid duplication of code.

**Comment by managerger** [comment]
Any updates on this?

**Comment by JanVargovsky** [comment]
@devmondo do you accept PR? I can convert it to use newer csproj format and target .NET Standard. Everyone is forced to implement it on his own now.

**Comment by devmondo** [comment]
@JanVargovsky thanks a lot and yes please 👍
