### ISSUE TITLE
Publish nuget package?

### ISSUE THREAD

**Issue by smasherprog** [devmondo/HangFire.SimpleInjector#16]
Are there any plans to publish the nuget package?

**Comment by ndicenso** [comment]
Any update on this?

**Comment by dcorriveau-omniscient** [comment]
I think you need to update the Nuget package. The latest version in Git supports SimpleInjector 4.0.7 but the current Nuget package still has a dependency on SimpleInjector.Extensions.ExecutionContextScoping which is deprecated.
Thanks.

**Comment by devmondo** [comment]
@/all anyone interested in helping on this ?

**Comment by zivillian** [comment]
What kind of help? Setting up an appveyor build, which produces a nuget package, which can be uploaded? Which version? How was this done until now? What has to be done, before creating a new version?

**Comment by devmondo** [comment]
@zivillian nothing much, I am not doing `.NET` since a long time now :) as I remember, it is just the code here on GitHub that I remember having on my machine.

**Comment by zivillian** [comment]
I ran the following two commands after patching `\src\HangFire.SimpleInjector\HangFire.SimpleInjector.csproj` with the attached patch.txt:
```
.\src\HangFire.SimpleInjector\_CreateNewNuGetPackage\DoNotModify\NuGet.exe restore .\src\HangFire.SimpleInjector.sln
.\src\HangFire.SimpleInjector\_CreateNewNuGetPackage\RunMeToUploadNuGetPackage.cmd
```
and selected `\src\HangFire.SimpleInjector\HangFire.SimpleInjector.csproj`

The output is attached, and if I'm correct the only todo is uploading this to nuget after renaming back to .nupkg.


[HangFire.SimpleInjector.csproj.patch](https://github.com/devmondo/HangFire.SimpleInjector/files/1201633/HangFire.SimpleInjector.csproj.patch.txt)
[Hangfire.SimpleInjector.1.3.1.nupkg.zip](https://github.com/devmondo/HangFire.SimpleInjector/files/1201630/Hangfire.SimpleInjector.1.3.1.nupkg.zip)

**Comment by devmondo** [comment]
@zivillian thank you very much! i uploaded it, thank god i still have my nuget account info ;)
