### ISSUE TITLE
Available on nuget?

### ISSUE THREAD

**Issue by Gillardo** [devmondo/HangFire.SimpleInjector#9]
Is this release available on nuget?  If i try to install the nuget version, i says that i have an error with referencing hangfire.core, but it is there.  Plus the nuget package was published in April and the latest changes on here (which i need), says created 3 months ago (September)

**Comment by EvilGamerX** [comment]
Along with this it would be nice to have a license added to this repo just to clear up and ambiguity about how it can be used.

**Comment by devmondo** [comment]
hi, 
sorry for the delay, but i had no time to work on this, i added the license and upgraded to latest dependencies per your advice :)

let me know if it works
